{"name": "[Title]case 01 正确的用户名密码登录", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\Appiunm_UI\\\\pytest20211010\\\\test_sutie_10\\\\login_suite\\\\test.jpg'", "trace": "self = <pytest20211010.test_sutie_10.login_suite.test_login.TestLogin object at 0x038BF290>\n\n    @allure.story(\"[Story]用户根据用户名密码登录系统\")\n    @allure.title(\"[Title]case 01 正确的用户名密码登录\")\n    @allure.testcase(url=\"http://47.107.178.45/zentao/www/index.php?m=bug&f=view&bugID=686\", name=\"用例地址\")\n    @allure.issue(url=\"http://47.107.178.45/zentao/www/index.php?m=bug&f=view&bugID=686\", name=\"bug地址\")\n    @allure.description(\"登录测试用例 执行人：李某\")\n    @allure.link(url=\"http://www.baidu.com\", name=\"百度一下，你就知道\")\n    # @allure.severity_level(\"normal\")\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_login_success(self):\n        step_01()\n        with allure.step(\"步骤二：输入用户名：admin\"):\n            pass\n        with allure.step(\"步骤三：输入密码：123456\"):\n            pass\n>       with open(r'D:\\Appiunm_UI\\pytest20211010\\test_sutie_10\\login_suite\\test.jpg', \"rb\") as img_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\Appiunm_UI\\\\pytest20211010\\\\test_sutie_10\\\\login_suite\\\\test.jpg'\n\nlogin_suite\\test_login.py:35: FileNotFoundError"}, "description": "登录测试用例 执行人：李某", "steps": [{"name": "步骤一：打开好再来电商系统", "status": "passed", "start": 1634110254978, "stop": 1634110254978}, {"name": "步骤二：输入用户名：admin", "status": "passed", "start": 1634110254978, "stop": 1634110254978}, {"name": "步骤三：输入密码：123456", "status": "passed", "start": 1634110254978, "stop": 1634110254978}], "start": 1634110254977, "stop": 1634110254978, "uuid": "dab18246-541d-4d83-bd30-04f24b9ff89c", "historyId": "c3ce9a706dadaa1c6af92ecd6237b620", "testCaseId": "fe27b844a99be01c36c828aa9a479fb0", "fullName": "login_suite.test_login.TestLogin#test_login_success", "labels": [{"name": "epic", "value": "[Epic]好再来电商系统"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "[Feature]好再来电商系统 V1.9.1"}, {"name": "story", "value": "[Story]用户根据用户名密码登录系统"}, {"name": "parentSuite", "value": "login_suite"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "9452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_suite.test_login"}], "links": [{"type": "link", "url": "http://www.baidu.com", "name": "百度一下，你就知道"}, {"type": "issue", "url": "http://47.107.178.45/zentao/www/index.php?m=bug&f=view&bugID=686", "name": "bug地址"}, {"type": "test_case", "url": "http://47.107.178.45/zentao/www/index.php?m=bug&f=view&bugID=686", "name": "用例地址"}]}